# k8s/03-backend.yaml

# 2. Despliegue del Backend
# Define cómo se debe ejecutar el contenedor de tu aplicación NestJS.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teslo-backend-deployment
  namespace: teslo-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teslo-backend
  template:
    metadata:
      labels:
        app: teslo-backend
    spec:
      containers:
      - name: teslo-backend
        # Esta imagen es la que acabas de subir a Docker Hub
        image: dmarmijosa/teslo-shop:latest 
        ports:
        - containerPort: 3000
        env:
          - name: DB_HOST
            value: "teslo-postgres-svc"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "TesloDB"
          - name: DB_USERNAME
            value: "postgres"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: teslo-db-secret
                key: DB_PASSWORD
          - name: HOST_API
            valueFrom:
              secretKeyRef:
                name: teslo-backend-secret
                key: HOST_API
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: teslo-backend-secret
                key: SECRET_PASSWORD